---
# @author khalil-Elf441

- name: install node curl
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    
- name: install node and config paths
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install 16
    sudo ln -s "$(which node)" "/usr/local/bin/node"
    sudo ln -s "$(which npm)" "/usr/local/bin/npm"
# Verify node and npm install
- name: check Node and npm installed version
  shell: |
    node --version && npm --version
  register: command_output
- debug: var=command_output.stdout_lines
  

- name: "install and configure pm2 path"
  become: yes
  shell: | 
    npm install pm2 -g
    export PATH=$PATH:$(npm config get prefix)/bin
- name: check pm2 installation
  become: yes
  shell: |
    export PATH=$PATH:$(npm config get prefix)/bin
    pm2 status
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines
