---
- name: "Creates backend app directory"
  file:
    path: ~/backend
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/backend

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm i
    
- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
    
- name: check pm2 status
  become: yes
  shell: |
    pm2 status
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines


  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ~/src/migrations
    TYPEORM_MIGRATIONS: ~/src/migrations/*.ts
    TYPEORM_ENTITIES: ~/src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-db-prod.cjqwbt35ugyf.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: postgres


