---
# - name: 'update and upgrade packages.'
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400

# - name: remove unneeded deps
#   become: yes
#   apt:
#     autoremove: yes

# - name: install pm2
#   become: yes
#   npm:
#     name: pm2
#     global: yes

- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .
    
- name: start app
  become: yes
  shell: |
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    npm install
    pm2 stop all
    pm2 start npm --name "udapeople-backend" -- run start

- name: "Set pm2 start as service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu

- name: check pm2 status
  become: yes
  shell: |
    pm2 describe "udapeople-backend"
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines
