---
# - name: 'update and upgrade packages.'
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400

# - name: remove unneeded deps
#   become: yes
#   apt:
#     autoremove: yes

# - name: install pm2
#   become: yes
#   npm:
#     name: pm2
#     global: yes

- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .
    
- name: start app
  become: yes
  shell: |
    npm i
    pm2 stop all
    pm2 start npm -- start
    
- name: check pm2 status
  become: yes
  shell: |
    pm2 status
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines


  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ~/src/migrations
    TYPEORM_MIGRATIONS: ~/src/migrations/*.ts
    TYPEORM_ENTITIES: ~/src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-db-prod.cjqwbt35ugyf.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: postgres
